id: 7301467ead6f4de692ac25b6e8721f1e
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_522-The_Dharani_of_the_Tathagata_Jnanolka-v1
  language: en
  author: ''
  volume: {}
